# ★第一部分，系统配置
mixed-port: 7891
redir-port: 17891
allow-lan: true
bind-address: '*'
mode: rule
log-level: silent
ipv6: false
external-controller: 0.0.0.0:9090
external-ui: dashboardB
#interface-name: en0

# ★第二部分，DNS配置
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - 'localhost.ptlogin2.qq.com'
    - 'dns.msftncsi.com'
    - 'www.msftncsi.com'
    - 'www.msftconnecttest.com'
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

# ★第三部分，代理配置
proxies:
  - name: "facebook"
    type: vmess
    server: us102.free2222.xyz
    port: 443
    uuid: 113ed49b-85cb-4eb7-a94e-95da956cf4bb
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    network: ws
    ws-path: /ray
    ws-headers: # 这一行后面不要写东西
      Host: us102.free2222.xyz #填你的主机名  

  - name: "1"
    type: vmess
    server: ge001.free2222.xyz
    port: 443
    uuid: 55139eb8-f598-4cdd-90e5-def733e8f999
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    network: ws
    ws-path: /ray
    ws-headers: # 这一行后面不要写东西
      Host: ge001.free2222.xyz #填你的主机名  

  - name: "2"
    type: vmess
    server: us1021.free2222.xyz
    port: 443
    uuid: 113ed49b-85cb-4eb7-a94e-95da956cf4bb
    alterId: 0
    cipher: auto
    udp: true
    tls: true
    # skip-cert-verify: true
    network: ws
    ws-path: /ray
    ws-headers: # 这一行后面不要写东西
      Host: us102.free2222.xyz #填你的主机名  

  - name: "3"
    type: vmess
    server: cdn1.free2222.xyz
    port: 443
    uuid: 3042bf92-26a7-4de8-adce-05c0fad54341
    alterId: 0
    cipher: auto
    #udp: true
    tls: true
    # skip-cert-verify: true
    network: ws
    ws-path: /ray
    ws-headers: # 这一行后面不要写东西
      Host: cdn1.free2222.xyz #填你的主机名  

  - name: "4"
    type: vmess
    server: cloudflare.com
    port: 443
    uuid: 113ed49b-85cb-4eb7-a94e-95da956cf4bb
    alterId: 0
    cipher: auto
    # udp: true
    tls: true
    # skip-cert-verify: true
    network: ws
    ws-path: /ray
    ws-headers: # 这一行后面不要写东西
      Host: us102.free2222.xyz #填你的主机名  

  - name: "5"
    type: vmess
    server: 104.19.0.10
    port: 443
    uuid: 55139eb8-f598-4cdd-90e5-def733e8f999
    alterId: 0
    cipher: auto
    # udp: true
    tls: true
    # skip-cert-verify: true
    network: ws
    ws-path: /ray
    ws-headers: # 这一行后面不要写东西
      Host: ge001.free2222.xyz #填你的主机名  

  - name: "6"
    type: vmess
    server: cloudflare.com
    port: 443
    uuid: 55139eb8-f598-4cdd-90e5-def733e8f999
    alterId: 0
    cipher: auto
    # udp: true
    tls: true
    # skip-cert-verify: true
    network: ws
    ws-path: /ray
    ws-headers: # 这一行后面不要写东西
      Host: ge001.free2222.xyz #填你的主机名  
  
 - {"name":"101","server":"185.108.106.188","type":"ss","country":"FR","port":39772,"password":"CUndSZnYsPKcu6Kj8THVMBHD","cipher":"aes-256-gcm"}
 - {"name":"102","server":"185.134.23.53","type":"ss","country":"GB","port":39772,"password":"CUndSZnYsPKcu6Kj8THVMBHD","cipher":"aes-256-gcm"}
 - {"name":"103","server":"trojan.yangxifang.tk","type":"trojan","country":"JP","port":443,"password":"hPqAIpjl","skip-cert-verify":true,"udp":true}
 - {"name":"104","server":"tky3.ssgnode.ga","type":"trojan","country":"JP","port":443,"password":"23115_5a451f03","skip-cert-verify":true,"udp":true}
 - {name: 105, server: v2.linn.ink, port: 22600, type: vmess, uuid: ce272424-fe15-42cd-8903-355dd33b0451, alterId: 100, cipher: auto, tls: false}
 - {name: 106, server: 139.226.163.144, port: 10001, type: vmess, uuid: 2e6fe034-aeaf-4b7d-9c28-7d5465f58837, alterId: 1, cipher: auto, tls: false}
 - {name: 107, server: 104.19.32.10, port: 443, type: vmess, uuid: 55139eb8-f598-4cdd-90e5-def733e8f999, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray, ws-headers: {Host: ge001.free2222.xyz}}
 - {name: 108, server: 104.19.64.20, port: 443, type: vmess, uuid: 55139eb8-f598-4cdd-90e5-def733e8f999, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray, ws-headers: {Host: ge001.free2222.xyz}}
 - {name: 109, server: us102.free2222.xyz, port: 443, type: vmess, uuid: 113ed49b-85cb-4eb7-a94e-95da956cf4bb, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray, ws-headers: {Host: us102.free2222.xyz}}
 - {name: 110, server: us103.free2222.xyz, port: 443, type: vmess, uuid: f2075a98-f9c8-4eae-81dc-7c0d5fc1dfed, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray, ws-headers: {Host: us103.free2222.xyz}}
 - {name: 111, server: cloudflare.com, port: 443, type: vmess, uuid: 55139eb8-f598-4cdd-90e5-def733e8f999, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray, ws-headers: {Host: ge001.free2222.xyz}}
 - {name: 112, server: us102.free2222.xyz, port: 443, type: vmess, uuid: 113ed49b-85cb-4eb7-a94e-95da956cf4bb, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray, ws-headers: {Host: us102.free2222.xyz}}
 - {name: 113, server: adman01.free2222.xyz, port: 443, type: vmess, uuid: 1564abce-bde7-435a-9ab4-97565eb17734, alterId: 0, cipher: auto, tls: true, network: ws, ws-path: /ray, ws-headers: {Host: adman01.free2222.xyz}}




proxy-groups:
  - name: "AirGroup"
    type: url-test
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
     - "1"
     - "2"
     - "3"
     - "4"
     - "5"
     - "6"
     - "101"
     - "102"
     - "103"
     - "104"
     - "105"
     - "106"
     - "107"
     - "108"
     - "109"
     - "110"
     - "111"
     - "112"
     - "113"
     # - "114"
     # - "115"
     # - "116"
     # - "117"
     # - "118"
     # - "119"
     # - "120"
     # - "121"
     # - "122"
    use: 
     - au
     - us
     - ca
     - jp
     - sg
     - ru
     - ch
     - de
     - fr
     - gb
     - nl
          

  - name: "load-balance"
    type: load-balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
     - "1"
     - "2"
     - "3"
     - "4"
     - "5"
     - "6"
     - "101"
     - "102"
     - "103"
     - "104"
     - "105"
     - "106"
     - "107"
     - "108"
     - "109"
     - "110"
     - "111"
     - "112"
     - "113"
     # - "114"
     # - "115"
     # - "116"
     # - "117"
     # - "118"
     # - "119"
     # - "120"
     # - "121"
     # - "122"
    
    use: 
     - au
     - us
     - ca
     - jp
     - sg
     - ru
     - ch
     - de
     - fr
     - gb
     - nl

  - name: "load-balance-free"
    type: load-balance
    url: 'http://www.gstatic.com/generate_204'
    interval: 300
    proxies:
     - "1"
     - "2"
     - "3"
     - "4"
     - "5"
     - "6"


  - name: "FuckWall"
    type: select
    proxies:
      - load-balance
      - load-balance-free
      - AirGroup
      - "1"
      - "2"
      - "3"
      - "4"
      - "5"
      - "6"
      - "101"
      - "102"
      - "103"
      - "104"
      - "105"
      - "106"
      - "107"
      - "108"
      - "109"
      - "110"
      - "111"
      - "112"
      - "113"
      # - "114"
      # - "115"
      # - "116"
      # - "117"
      # - "118"
      # - "119"
      # - "120"
      # - "121"
      # - "122"
      
    use:
      - au
      - us
      - ca
      - jp
      - sg
      - ru
      - ch
      - de
      - fr
      - gb
      - nl
      
  - name: "Just4FaceBook"
    type: select
    proxies:
      - "facebook"

  - name: "Final"
    type: select
    proxies:
      - FuckWall
      - DIRECT
      

proxy-providers: 
#^^^^^^^^^^^^^^^^^PoorStudio^^^^^^^^ 
  "au":
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=AU"
    path: proxypoolsstest.herokuapp.com/provider-au.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  
  us:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=US"
    path: proxypoolsstest.herokuapp.com/provider-us.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ca:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=CA"
    path: proxypoolsstest.herokuapp.com/provider-ca.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  jp:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=JP"
    path: proxypoolsstest.herokuapp.com/provider-jp.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  sg:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=SG"
    path: proxypoolsstest.herokuapp.com/provider-sg.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ru:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=RU"
    path: proxypoolsstest.herokuapp.com/provider-ru.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  ch:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=CH"
    path: proxypoolsstest.herokuapp.com/provider-ch.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  de:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=DE"
    path: proxypoolsstest.herokuapp.com/provider-de.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  fr:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=FR"
    path: proxypoolsstest.herokuapp.com/provider-fr.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  gb:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=GB"
    path: proxypoolsstest.herokuapp.com/provider-gb.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204
  nl:
    type: http
    url: "https://proxypoolsstest.herokuapp.com/clash/proxies?c=NL"
    path: proxypoolsstest.herokuapp.com/provider-nl.yaml
    health-check:
      enable: true
      interval: 600
      url: http://www.gstatic.com/generate_204 
  # "PoorStudio":
    # type: http
    # url: "https://proxypoolsstest.herokuapp.com"
    # interval: 3600
    # path: ./clash/config
    # health-check:
      # enable: true
      # interval: 600
      # url: http://www.gstatic.com/generate_204 

#vvvvvvvvvvvvvvvvvvvvvvPoorStudiovvvvvvvvvvvvvvvvvvvvvvv




# ★第四部分，规则配置
rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400

rules:
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - DOMAIN-SUFFIX,googleapis.cn,FuckWall
  - DOMAIN-KEYWORD,facebook,Just4FaceBook
  - DOMAIN-KEYWORD,oculus,Just4FaceBook
  - DOMAIN-KEYWORD,oculuscdn,Just4FaceBook
  - DOMAIN-SUFFIX,myip.com,Just4FaceBook
  #- RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,FuckWall
  - RULE-SET,proxy,FuckWall
  - RULE-SET,direct,DIRECT
  - RULE-SET,telegramcidr,FuckWall
  - GEOIP,CN,DIRECT
#  - MATCH,FuckWall
  - MATCH,Final
