port: 40000
mode: rule
log-level: info
external-controller: 127.0.0.1:40001
proxies:
- name: Youtube不良林
  type: http
  server: buliang0.tk
  port: 6666
- name: 40010
  type: ss
  server: ss4.ssrsub.one
  port: 5443
  cipher: aes-128-gcm
  password: suo.yt/ssrsub
- name: 40011
  type: vmess
  server: 204.124.181.118
  port: 61173
  cipher: auto
  uuid: 9d1043a6-e87e-4bb7-8858-c1185e9c0c3b
  alterId: 8
  network: tcp
  ws-path: /
  ws-headers:
    Host: ''
- name: 40012
  type: vmess
  server: 138.201.150.52
  port: 33957
  cipher: auto
  uuid: 89cee221-b06c-46c5-f0d7-4fd3f4740b97
  alterId: 64
  network: tcp
  ws-path: /
  ws-headers:
    Host: ''
- name: 40013
  type: ss
  server: 51.195.62.220
  port: 811
  cipher: chacha20-ietf-poly1305
  password: G!yBwPWH3Vao
- name: 40014
  type: ss
  server: 81.19.208.107
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 40015
  type: ss
  server: 198.8.92.84
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 40016
  type: ss
  server: 66.115.175.37
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 40017
  type: ss
  server: 84.17.35.78
  port: 33992
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6
- name: 40018
  type: ss
  server: 198.147.22.87
  port: 33998
  cipher: aes-256-gcm
  password: NHwQTPLCfaTMSqTnU3mjcSxe
- name: 40019
  type: ss
  server: 198.8.92.84
  port: 44945
  cipher: aes-256-gcm
  password: F5bKkb9ggkLx4JbQrbLn7LjZ
- name: 40020
  type: vmess
  server: c23s3.jamjams.net
  port: 61173
  cipher: auto
  uuid: 9d1043a6-e87e-4bb7-8858-c1185e9c0c3b
  alterId: 8
  network: tcp
  ws-path: /
  ws-headers:
    Host: ''
- name: 40021
  type: vmess
  server: c23s801.jamjams.net
  port: 61173
  cipher: auto
  uuid: 9d1043a6-e87e-4bb7-8858-c1185e9c0c3b
  alterId: 8
  network: tcp
  ws-path: /
  ws-headers:
    Host: ''
- name: 40022
  type: vmess
  server: 23.83.227.198
  port: 61173
  cipher: auto
  uuid: 9d1043a6-e87e-4bb7-8858-c1185e9c0c3b
  alterId: 8
  network: tcp
  ws-path: /
  ws-headers:
    Host: ''
proxy-groups:
- name: Proxy2
  type: select
  proxies:
  - Youtube不良林
- name: proxy40010
  type: select
  proxies:
  - 40010
- name: proxy40011
  type: select
  proxies:
  - 40011
- name: proxy40012
  type: select
  proxies:
  - 40012
- name: proxy40013
  type: select
  proxies:
  - 40013
- name: proxy40014
  type: select
  proxies:
  - 40014
- name: proxy40015
  type: select
  proxies:
  - 40015
- name: proxy40016
  type: select
  proxies:
  - 40016
- name: proxy40017
  type: select
  proxies:
  - 40017
- name: proxy40018
  type: select
  proxies:
  - 40018
- name: proxy40019
  type: select
  proxies:
  - 40019
- name: proxy40020
  type: select
  proxies:
  - 40020
- name: proxy40021
  type: select
  proxies:
  - 40021
- name: proxy40022
  type: select
  proxies:
  - 40022
rules:
- SRC-PORT,40010,proxy40010
- SRC-PORT,40011,proxy40011
- SRC-PORT,40012,proxy40012
- SRC-PORT,40013,proxy40013
- SRC-PORT,40014,proxy40014
- SRC-PORT,40015,proxy40015
- SRC-PORT,40016,proxy40016
- SRC-PORT,40017,proxy40017
- SRC-PORT,40018,proxy40018
- SRC-PORT,40019,proxy40019
- SRC-PORT,40020,proxy40020
- SRC-PORT,40021,proxy40021
- SRC-PORT,40022,proxy40022
